# Setup
title:               Chaincode Labs Research
tagline:             
description:         
url:                 https://research.chaincode.com
baseurl:             ''
paginate:            5
permalink:           pretty
repository:          chaincodelabs/research-site

# About/contact
author:
  name:              Chaincode Labs Research
  url:               research.chaincode.com
  email:             nikki@chaincode.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
